// GENERATED by build.py from tokens/themes.json -- do not edit.
// brick: backman-design/dist/tokens.ts

export const CONTRACT = ["ground", "panel", "raised", "ink", "ink-2", "line", "line-2", "accent", "accent-2", "gain", "warn", "loss"] as const;
export type TokenName = (typeof CONTRACT)[number];
export const DEFAULT_DARK = "shield";
export const DEFAULT_LIGHT = "windowwall";

export const THEMES = {
  "shield": {
    "label": "Shield",
    "mode": "dark",
    "lightTwin": "windowwall",
    "colors": {
      "ground": "#191818",
      "panel": "#353839",
      "raised": "#686968",
      "ink": "#D8D5D2",
      "ink-2": "#9D9B98",
      "line": "#686968",
      "line-2": "#9D9B98",
      "accent": "#AFA238",
      "accent-2": "#9EB4DB",
      "gain": "#969E62",
      "warn": "#AFA238",
      "loss": "#C4685C"
    }
  },
  "greatroom": {
    "label": "Great Room",
    "mode": "dark",
    "lightTwin": "windowwall",
    "colors": {
      "ground": "#1A1514",
      "panel": "#3B2519",
      "raised": "#643C23",
      "ink": "#CAB899",
      "ink-2": "#8F8779",
      "line": "#643C23",
      "line-2": "#8F8779",
      "accent": "#CD9458",
      "accent-2": "#AA572A",
      "gain": "#969E62",
      "warn": "#CD9458",
      "loss": "#C4685C"
    }
  },
  "ledgestone": {
    "label": "Ledgestone",
    "mode": "dark",
    "lightTwin": "windowwall",
    "colors": {
      "ground": "#3A3737",
      "panel": "#5F5245",
      "raised": "#686968",
      "ink": "#E4E7E2",
      "ink-2": "#ADB1B6",
      "line": "#686968",
      "line-2": "#ADB1B6",
      "accent": "#ADB1B6",
      "accent-2": "#8F8779",
      "gain": "#969E62",
      "warn": "#CAB899",
      "loss": "#C4685C"
    }
  },
  "drone": {
    "label": "Drone",
    "mode": "dark",
    "lightTwin": "windowwall",
    "colors": {
      "ground": "#191818",
      "panel": "#383B23",
      "raised": "#5B4635",
      "ink": "#D8D5D2",
      "ink-2": "#9D9B98",
      "line": "#5B4635",
      "line-2": "#9D9B98",
      "accent": "#969E62",
      "accent-2": "#AFA238",
      "gain": "#969E62",
      "warn": "#AFA238",
      "loss": "#C4685C"
    }
  },
  "windowwall": {
    "label": "Window Wall",
    "mode": "light",
    "lightTwin": null,
    "colors": {
      "ground": "#E4E7E2",
      "panel": "#CAB899",
      "raised": "#ADB1B6",
      "ink": "#1A1514",
      "ink-2": "#5F5245",
      "line": "#ADB1B6",
      "line-2": "#5F5245",
      "accent": "#643C23",
      "accent-2": "#AA572A",
      "gain": "#2F6B45",
      "warn": "#AA572A",
      "loss": "#A8352A"
    }
  },
  "blueprint": {
    "label": "Blueprint",
    "mode": "light",
    "lightTwin": null,
    "colors": {
      "ground": "#F1EFE4",
      "panel": "#E7E4D5",
      "raised": "#FAF8F0",
      "ink": "#14304F",
      "ink-2": "#4A6D9E",
      "line": "#4A6D9E",
      "line-2": "#4A6D9E",
      "accent": "#8E5900",
      "accent-2": "#6B4400",
      "gain": "#2F6B45",
      "warn": "#8E5900",
      "loss": "#A33A2E"
    }
  },
  "pressbox": {
    "label": "Press Box",
    "mode": "light",
    "lightTwin": null,
    "colors": {
      "ground": "#EBE9E2",
      "panel": "#F4F2EC",
      "raised": "#FFFFFF",
      "ink": "#16130F",
      "ink-2": "#4A453C",
      "line": "#B8B4A8",
      "line-2": "#B8B4A8",
      "accent": "#A3271E",
      "accent-2": "#7E1D16",
      "gain": "#1E5631",
      "warn": "#A3271E",
      "loss": "#A3271E"
    }
  }
} as const;

export type ThemeName = keyof typeof THEMES;

export function theme(name: ThemeName = DEFAULT_DARK as ThemeName) {
  const t = THEMES[name];
  if (!t) throw new Error(`unknown theme ${name}`);
  return t;
}
